import '../styles/globals.css';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useState } from 'react';


import BottomNavigation from '@mui/material/BottomNavigation';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import HomeIcon from '@mui/icons-material/Home';
import FavoriteIcon from '@mui/icons-material/Favorite';
import NewspaperIcon from '@mui/icons-material/Newspaper';



function MyApp({ Component, pageProps }) {
  const router = useRouter();
  
  const getRouteIndex = (value) => {
    console.log(value,'<<<')
    switch (value) {
      case '/': 
        return 2;
      case '/news':
        return 1;
      case '/':
        return 2;
      default:
        return 2;
    }
  }
  const changeRoute = (value) => {
    switch (value) {
      case 0: 
        router.push('/')
        return;
      case 1:
        router.push('/news')
        return;
      case 2:
        router.push('/')
        return
      default:
        router.push('/')
        break
    }
  }

  const [value, setValue] = useState(getRouteIndex(router.pathname));


  // return <Component {...pageProps} />
  return (
    <div className="h-screen">
      <Head>
        <title>Most Popular NYT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Component {...pageProps} />
      </main>

      <BottomNavigation
            className="w-full fixed bottom-0 border-t-[1px]"
            showLabels
            value={value}
            onChange={(event, newValue) => {
              setValue(newValue);
              changeRoute(newValue);
            }}
          >
              <BottomNavigationAction label="Favorites" icon={<FavoriteIcon />} />
              <BottomNavigationAction label="News" icon={<NewspaperIcon />} />
              <BottomNavigationAction label="Home" icon={<HomeIcon />} />
        </BottomNavigation>
    </div>
  )
}

export default MyApp
