import '../styles/globals.css';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { Provider } from 'react-redux';
import store from '../store'

import BottomNavigation from '@mui/material/BottomNavigation';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import HomeIcon from '@mui/icons-material/Home';
import NewspaperIcon from '@mui/icons-material/Newspaper';

import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';

import ArrowBackIosIcon from '@mui/icons-material/ArrowBackIos';

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  const getRouteIndex = (value) => {
    switch (value) {
      case '/': 
        return 1;
      case '/news':
        return 0;
      case '/news/[id]':
        return 0
      default:
        return 1;
    }
  }

  console.log(router.pathname)
  const changeRoute = (value) => {
    switch (value) {
      case 0: 
        router.push('/news')
        return;
      case 1:
        router.push('/')
        return;
      default:
        router.push('/')
        break
    }
  }

  const [value, setValue] = useState(getRouteIndex(router.pathname));

  return (
    <Provider store={store}>
      <div className="h-screen">
        <Head>
          <title>Most Popular NYT</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <AppBar position="fixed">
          <Toolbar variant="dense">
            {
              router.pathname.includes('id') ?             
              <IconButton 
                onClick={(e) => {
                  e.preventDefault();
                  changeRoute(0);
                }}
                edge="start" color="inherit" aria-label="menu" sx={{ mr: 2 }}>
                  <ArrowBackIosIcon /> 
              </IconButton> : ""
            }

            <Typography variant="h6" color="inherit" component="div">
              {router.pathname === '/' ? "HOME" : 'NEWS'}
            </Typography>
          </Toolbar>
        </AppBar>

        <main>
          <Component {...pageProps} />
        </main>

        <BottomNavigation
              className="w-full fixed bottom-0 border-t-[1px]"
              showLabels
              value={value}
              onChange={(event, newValue) => {
                setValue(newValue);
                changeRoute(newValue);
              }}
            >
                <BottomNavigationAction label="News" icon={<NewspaperIcon />} />
                <BottomNavigationAction label="Home" icon={<HomeIcon />} />
          </BottomNavigation>
      </div>
    </Provider>

  )
}

export default MyApp
